<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GeneratePackageOnBuild>True</GeneratePackageOnBuild>
		<Title>SeaConf</Title>
		<Description>A simple library for working with application settings.</Description>
		<Authors>ns-88</Authors>
		<Copyright>MIT</Copyright>
		<PackageProjectUrl>https://github.com/ns-88/SeaConf</PackageProjectUrl>
		<RepositoryUrl>https://github.com/ns-88/SeaConf</RepositoryUrl>
		<NeutralLanguage>en</NeutralLanguage>
		<RepositoryType>git</RepositoryType>
		<PackageReadmeFile>readme.md</PackageReadmeFile>
		<Version>1.0.5</Version>
		<IsPackable>true</IsPackable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core\SeaConf.Core.Common\SeaConf.Core.Common.csproj" />
		<ProjectReference Include="..\Core\Sources\SeaConf.Core.Sources.MemorySource\SeaConf.Core.Sources.MemorySource.csproj" />
		<ProjectReference Include="..\Core\Sources\SeaConf.Core.Sources.RegistrySource\SeaConf.Core.Sources.RegistrySource.csproj" />
		<ProjectReference Include="..\Core\Sources\SeaConf.Core.Sources.XmlSource\SeaConf.Core.Sources.XmlSource.csproj" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\readme.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<Compile Update="Configurations\ConfigurationComponents.cs">
			<DependentUpon>Configuration.cs</DependentUpon>
		</Compile>
		<Compile Update="Configurations\ConfigurationList.cs">
			<DependentUpon>Configuration.cs</DependentUpon>
		</Compile>
	</ItemGroup>

</Project>