//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSettingsMini.Infrastructure {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AppSettingsMini.Infrastructure.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найден конструктор с требуемыми аргументами в типе &quot;{0}&quot;..
        /// </summary>
        internal static string CtorWithRequiredArgsNotFound {
            get {
                return ResourceManager.GetString("CtorWithRequiredArgsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось удалить ключ реестра. Наименование ключа: &quot;{0}&quot;..
        /// </summary>
        internal static string FailedDeleteRegistryKey {
            get {
                return ResourceManager.GetString("FailedDeleteRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось получить значение свойства &quot;{0}&quot;. Модель &quot;{1}&quot;..
        /// </summary>
        internal static string FailedGetPropertyValue {
            get {
                return ResourceManager.GetString("FailedGetPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось получить ключ реестра &quot;{0}&quot;..
        /// </summary>
        internal static string FailedGetRegistryKey {
            get {
                return ResourceManager.GetString("FailedGetRegistryKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось получить значение свойства &quot;{0}&quot;. Модель &quot;{1}&quot;..
        /// </summary>
        internal static string FailedLoadPropertyValue {
            get {
                return ResourceManager.GetString("FailedLoadPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить настройки из источника..
        /// </summary>
        internal static string FailedLoadSettingsFromSource {
            get {
                return ResourceManager.GetString("FailedLoadSettingsFromSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось загрузить xml документ..
        /// </summary>
        internal static string FailedLoadXmlDocument {
            get {
                return ResourceManager.GetString("FailedLoadXmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить значение свойства &quot;{0}&quot;. Модель &quot;{1}&quot;..
        /// </summary>
        internal static string FailedSavePropertyValue {
            get {
                return ResourceManager.GetString("FailedSavePropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить настройки в источник..
        /// </summary>
        internal static string FailedSaveSettingsToSource {
            get {
                return ResourceManager.GetString("FailedSaveSettingsToSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось сохранить xml документ..
        /// </summary>
        internal static string FailedSaveXmlDocument {
            get {
                return ResourceManager.GetString("FailedSaveXmlDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось установить значение свойства &quot;{0}&quot;. Модель &quot;{1}&quot;..
        /// </summary>
        internal static string FailedSetPropertyValue {
            get {
                return ResourceManager.GetString("FailedSetPropertyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не удалось привести значение типа &quot;{0}&quot; к типу &quot;{1}&quot;..
        /// </summary>
        internal static string FailedToCastTypeValue {
            get {
                return ResourceManager.GetString("FailedToCastTypeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Метод &quot;{0}&quot; не найден..
        /// </summary>
        internal static string MethodNotFound {
            get {
                return ResourceManager.GetString("MethodNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель настроек с типом &quot;{0}&quot; уже зарегистрирована..
        /// </summary>
        internal static string ModelAlreadyRegistered {
            get {
                return ResourceManager.GetString("ModelAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Инициализация модели &quot;{0}&quot; не выполнена..
        /// </summary>
        internal static string ModelInitializationFailed {
            get {
                return ResourceManager.GetString("ModelInitializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель &quot;{0}&quot; не инициализирована..
        /// </summary>
        internal static string ModelNotInitialized {
            get {
                return ResourceManager.GetString("ModelNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель с типом &quot;{0}&quot; не зарегистрирована..
        /// </summary>
        internal static string ModelNotRegistered {
            get {
                return ResourceManager.GetString("ModelNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствуют зарегистрированные модели настроек..
        /// </summary>
        internal static string NotFoundRegisteredModels {
            get {
                return ResourceManager.GetString("NotFoundRegisteredModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свойство &quot;{0}&quot; не поддерживает чтение..
        /// </summary>
        internal static string PropertyIsNotReadable {
            get {
                return ResourceManager.GetString("PropertyIsNotReadable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдено свойство в модели. Наименование свойства &quot;{0}&quot;..
        /// </summary>
        internal static string PropertyNotFound {
            get {
                return ResourceManager.GetString("PropertyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Свойство &quot;{0}&quot; не найдено в типе &quot;{1}&quot;..
        /// </summary>
        internal static string PropertyNotFoundInType {
            get {
                return ResourceManager.GetString("PropertyNotFoundInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип свойства не является корректным. Ожидался тип &quot;{0}&quot;, но был получен &quot;{1}&quot;..
        /// </summary>
        internal static string PropertyTypeNotCorrect {
            get {
                return ResourceManager.GetString("PropertyTypeNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не задано значение свойства &quot;{0}&quot; в типе &quot;{1}&quot;..
        /// </summary>
        internal static string PropertyValueNotSetInType {
            get {
                return ResourceManager.GetString("PropertyValueNotSetInType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение ключа реестра не указано. Наименование ключа: &quot;{0}&quot;..
        /// </summary>
        internal static string RegistryKeyValueNotSpecified {
            get {
                return ResourceManager.GetString("RegistryKeyValueNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корневой элемент коллекции с именем &quot;{0}&quot; не существует..
        /// </summary>
        internal static string RootCollectionElementNotExist {
            get {
                return ResourceManager.GetString("RootCollectionElementNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Строковое значение не может быть преобразовано к типу &quot;{0}&quot;. Значение &quot;{1}&quot;..
        /// </summary>
        internal static string StringValueCannotConvertedToType {
            get {
                return ResourceManager.GetString("StringValueCannotConvertedToType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Атрибут &quot;value&quot; не найден. Родительский элемент: &quot;{0}&quot;..
        /// </summary>
        internal static string ValueAttributeNotFound {
            get {
                return ResourceManager.GetString("ValueAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Провайдер чтения и записи значения для типа &quot;{0}&quot; уже зарегистрирован..
        /// </summary>
        internal static string ValueProviderAlreadyRegistered {
            get {
                return ResourceManager.GetString("ValueProviderAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Провайдер чтения и записи значения для типа &quot;{0}&quot; не был создан..
        /// </summary>
        internal static string ValueProviderNotCreated {
            get {
                return ResourceManager.GetString("ValueProviderNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найден провайдер чтения и записи значения для типа &quot;{0}&quot;..
        /// </summary>
        internal static string ValueProviderNotFound {
            get {
                return ResourceManager.GetString("ValueProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Элемент xml-документа с именем &quot;{0}&quot; не существует..
        /// </summary>
        internal static string XmlDocumentElementNotExist {
            get {
                return ResourceManager.GetString("XmlDocumentElementNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствует корневой элемент xml-документа..
        /// </summary>
        internal static string XmlDocumentRootElementIsMissing {
            get {
                return ResourceManager.GetString("XmlDocumentRootElementIsMissing", resourceCulture);
            }
        }
    }
}
